# Generated by Django 2.0.2 on 2018-02-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180227_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
