# Generated by Django 2.0.2 on 2018-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20180220_1728'),
        ('song', '0003_song_melon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록'),
        ),
    ]
