# Generated by Django 2.0.2 on 2018-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='발매일'),
        ),
    ]
