# Generated by Django 2.0.2 on 2018-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20180206_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Artist ID'),
        ),
    ]
